version: "3.9"

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    privileged: true  # Puede no ser necesario en todos los casos
    stop_grace_period: 30s
    shm_size: "512mb"

    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined

    devices:
      - /dev/bus/usb:/dev/bus/usb               # Coral USB
      - /dev/apex_0:/dev/apex_0                 # Coral PCIe
      - /dev/video11:/dev/video11               # Cámara V4L2 (por ejemplo RPi 4B)
      - /dev/dri/renderD128:/dev/dri/renderD128 # Aceleración por hardware Intel
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ruta/a/tu/config:/config
      - /ruta/a/tu/almacenamiento:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

    ports:
      - "8971:8971"       # Interfaz web
      - "5000:5000"     # Acceso interno no autenticado (opcional)
      - "8554:8554"       # RTSP
      - "8555:8555/tcp"   # WebRTC TCP
      - "8555:8555/udp"   # WebRTC UDP

    environment:
      FRIGATE_RTSP_PASSWORD: "asd12345"
